import React, { useEffect, useState } from "react";
import { Button, Signal } from "../../ui";
type OnboardingState = { completed: boolean; hints: { trail: boolean; detour: boolean; portal: boolean } };
const initialOnboardingState: OnboardingState = { completed: false, hints: { trail: false, detour: false, portal: false } };
const ONBOARDING_KEY = "tabyrinth.onboarding";
async function readOnboarding(): Promise<OnboardingState> { const result = await chrome.storage.local.get(ONBOARDING_KEY); const state = result[ONBOARDING_KEY] as OnboardingState | undefined; return state?.completed !== undefined ? state : initialOnboardingState; }
async function writeOnboarding(state: OnboardingState): Promise<void> { await chrome.storage.local.set({ [ONBOARDING_KEY]: state }); }
const stages = [{ label: "INTRO", title: "Keep the useful path.", body: "TABYRINTH turns browsing drift into a quiet trail you can return to." }, { label: "TRAIL", title: "The trail follows you.", body: "Your current page sits at the edge. The pages behind it stay in order." }, { label: "DETOUR", title: "A detour is reversible.", body: "When a branch is safe to fold, TABYRINTH brings you back to the fork." }, { label: "PORTAL", title: "Leave the door open.", body: "Saved branches remain available when you need them again." }] as const;
export function Onboarding({ onComplete }: { onComplete?: () => void }) { const [stage, setStage] = useState(0); const [busy, setBusy] = useState(false); const current = stages[stage]; const finish = async () => { setBusy(true); await writeOnboarding({ ...initialOnboardingState, completed: true }); onComplete?.(); }; return <section className="onboarding" aria-labelledby="onboarding-title"><div className="onboarding-meta"><Signal label={current.label} state="active" /><span aria-live="polite">{stage + 1} / {stages.length}</span></div><div className="onboarding-copy"><h1 id="onboarding-title">{current.title}</h1><p>{current.body}</p></div><ol className="onboarding-steps" aria-label="Introduction progress">{stages.map((item, index) => <li key={item.label} data-current={index === stage}><span aria-hidden="true">{index === stage ? "◆" : "·"}</span><span>{item.label}</span></li>)}</ol><div className="onboarding-actions">{stage > 0 && <button type="button" className="text-control" onClick={() => setStage(stage - 1)}>Back</button>}<Button disabled={busy} onClick={() => stage === stages.length - 1 ? void finish() : setStage(stage + 1)}>{stage === stages.length - 1 ? "Start my first Quest" : "Continue"}</Button></div></section>; }
export function useOnboarding() { const [state, setState] = useState<OnboardingState | null>(null); useEffect(() => { void readOnboarding().then(setState); }, []); const complete = () => setState((previous) => ({ ...(previous ?? initialOnboardingState), completed: true })); const replay = () => { setState((previous) => { const next = { ...(previous ?? initialOnboardingState), completed: false }; void writeOnboarding(next); return next; }); }; return { state, complete, replay }; }
