import { describe, expect, it } from "vitest";
import { createPortalSnapshot, emptyPortalState, type Portal } from "./types";
import { portalReducer } from "./reducer";
const node = (id: string, parentNodeId: string | null, url = "https://same.test") => ({ id, questId: "q", parentNodeId, url, title: id, faviconUrl: null, disposition: "path" as const, status: "live" as const, createdAt: 1, updatedAt: 1 });
const portal = (): Portal => { const graph = { nodes: { a: node("a", null), b: node("b", "a"), c: node("c", "a") }, tabBindings: {} }; const snapshot = createPortalSnapshot(graph, "p", "q", "o", "a", "b", ["a", "b", "c"], 1); return { id: "p", questId: "q", title: "x", originNodeId: "o", branchRootNodeId: "a", nodeIds: ["a", "b", "c"], portalNodeId: "pn", portalTabId: null, status: "sealed", createdAt: 1, updatedAt: 1, snapshot, restoreStatus: "idle", restoredNodeIds: [], error: null }; };
describe("portal pure lifecycle contract", () => {
  it("requires persistence before close", () => { const p = portal(); expect(() => portalReducer(emptyPortalState(), { type: "CLOSE_STARTED", portalId: "p" })).toThrow(); let s = portalReducer(emptyPortalState(), { type: "SNAPSHOT_PERSISTED", portal: p, closeableNodeIds: p.nodeIds }); s = portalReducer(s, { type: "PORTAL_OPENED", portalId: "p", portalTabId: 9 }); expect(() => portalReducer(s, { type: "BRANCH_SEALED", portalId: "p" })).toThrow(); });
  it("retains snapshot on partial and duplicate restore", () => { const p = portal(); let s = portalReducer(emptyPortalState(), { type: "SNAPSHOT_PERSISTED", portal: p, closeableNodeIds: p.nodeIds }); s = portalReducer(s, { type: "RESTORE_STARTED", portalId: "p" }); s = portalReducer(s, { type: "RESTORE_PROGRESS", portalId: "p", nodeId: "b" }); s = portalReducer(s, { type: "RESTORE_PROGRESS", portalId: "p", nodeId: "b" }); s = portalReducer(s, { type: "RESTORE_FAILED", portalId: "p", reason: "boom" }); expect(s.portals.p.snapshot).toEqual(p.snapshot); expect(s.portals.p.restoredNodeIds).toEqual(["b"]); });
  it("marks manual Portal loss without deleting the recoverable snapshot", () => { const p = portal(); let s = portalReducer(emptyPortalState(), { type: "SNAPSHOT_PERSISTED", portal: p, closeableNodeIds: p.nodeIds }); s = portalReducer(s, { type: "PORTAL_TAB_LOST", portalId: "p" }); expect(s.portals.p.status).toBe("error"); expect(s.portals.p.portalTabId).toBeNull(); expect(s.portals.p.error).toBe("PORTAL_TAB_UNAVAILABLE"); expect(s.portals.p.snapshot).toEqual(p.snapshot); });
  it("preserves relationships and same URL nodes as distinct IDs", () => { const p = portal(); expect(p.snapshot.nodes.b.parentNodeId).toBe("a"); expect(p.snapshot.nodes.b).not.toBe(p.snapshot.nodes.c); expect(p.snapshot.nodes.b.url).toBe(p.snapshot.nodes.c.url); });
});
